# Generated by Django 4.1.1 on 2022-09-20 15:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 20, 15, 3, 46, 305585, tzinfo=datetime.timezone.utc))),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=690)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Payment_type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 20, 15, 3, 46, 305585, tzinfo=datetime.timezone.utc))),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('payment_name', models.CharField(max_length=960)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'payment_type',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 20, 15, 3, 46, 305585, tzinfo=datetime.timezone.utc))),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.BooleanField(null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=100)),
                ('certificate', models.CharField(max_length=99)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 20, 15, 3, 46, 305585, tzinfo=datetime.timezone.utc))),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Scopes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 20, 15, 3, 46, 305585, tzinfo=datetime.timezone.utc))),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('scope_value', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scope', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scopes',
            },
        ),
        migrations.CreateModel(
            name='Profiles_Payment_type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 20, 15, 3, 46, 305585, tzinfo=datetime.timezone.utc))),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('payment_number', models.CharField(blank=True, max_length=960, null=True)),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_payment_type', to='api_user.payment_type')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_payment_type', to='api_user.profiles')),
            ],
            options={
                'db_table': 'profiles_payment_type',
            },
        ),
        migrations.AddField(
            model_name='profiles',
            name='payment_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile', through='api_user.Profiles_Payment_type', to='api_user.payment_type'),
        ),
        migrations.CreateModel(
            name='Accounts_infor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 20, 15, 3, 46, 305585, tzinfo=datetime.timezone.utc))),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('avatar', models.CharField(blank=True, max_length=950, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_infor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_infor',
            },
        ),
        migrations.AddField(
            model_name='accounts',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='api_user.profiles'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='api_user.roles'),
        ),
    ]
