# Generated by Django 4.1.1 on 2022-09-20 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 20, 15, 13, 52, 400460, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accounts_infor',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 20, 15, 13, 52, 400460, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment_type',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 20, 15, 13, 52, 400460, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 20, 15, 13, 52, 400460, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profiles_payment_type',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 20, 15, 13, 52, 400460, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='roles',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 20, 15, 13, 52, 400460, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scopes',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 20, 15, 13, 52, 400460, tzinfo=datetime.timezone.utc)),
        ),
    ]
