# Generated by Django 4.1.1 on 2022-09-20 15:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_alter_accounts_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 20, 15, 26, 58, 622856, tzinfo=datetime.timezone.utc), default=None),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='api_user.profiles'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='api_user.roles'),
        ),
        migrations.AlterField(
            model_name='accounts_infor',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_infor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accounts_infor',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 20, 15, 26, 58, 622856, tzinfo=datetime.timezone.utc), default=None),
        ),
        migrations.AlterField(
            model_name='payment_type',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 20, 15, 26, 58, 622856, tzinfo=datetime.timezone.utc), default=None),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 20, 15, 26, 58, 622856, tzinfo=datetime.timezone.utc), default=None),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='payment_type',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='profile', through='api_user.Profiles_Payment_type', to='api_user.payment_type'),
        ),
        migrations.AlterField(
            model_name='profiles_payment_type',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 20, 15, 26, 58, 622856, tzinfo=datetime.timezone.utc), default=None),
        ),
        migrations.AlterField(
            model_name='profiles_payment_type',
            name='payment_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_payment_type', to='api_user.payment_type'),
        ),
        migrations.AlterField(
            model_name='profiles_payment_type',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_payment_type', to='api_user.profiles'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 20, 15, 26, 58, 622856, tzinfo=datetime.timezone.utc), default=None),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scopes',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scope', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scopes',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 20, 15, 26, 58, 622856, tzinfo=datetime.timezone.utc), default=None),
        ),
    ]
