# Generated by Django 4.1.1 on 2022-10-06 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0005_alter_accounts_create_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts_Roles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('create_at',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='role',
        ),
        migrations.RemoveField(
            model_name='scopes',
            name='account',
        ),
        migrations.RemoveField(
            model_name='scopes',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='scopes',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='scopes',
            name='update_at',
        ),
        migrations.AddField(
            model_name='profiles',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='avatar',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='district',
            field=models.CharField(blank=True, default=None, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='district_code',
            field=models.CharField(blank=True, default=None, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='province',
            field=models.CharField(blank=True, default=None, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='province_code',
            field=models.CharField(blank=True, default=None, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='ward',
            field=models.CharField(blank=True, default=None, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='ward_code',
            field=models.CharField(blank=True, default=None, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='scopes',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='api_user.roles'),
        ),
        migrations.AlterField(
            model_name='scopes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scopes',
            name='scope_value',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Accounts_infor',
        ),
        migrations.AddField(
            model_name='accounts_roles',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounts_roles',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_role', to='api_user.roles'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='roles',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='account', through='api_user.Accounts_Roles', to='api_user.roles'),
        ),
    ]
