# Generated by Django 4.1.1 on 2022-10-20 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0009_scopes_create_at_scopes_is_active_scopes_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles_payment_type',
            name='payment_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_payment_type', to='api_user.payment_type'),
        ),
        migrations.AlterField(
            model_name='profiles_payment_type',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_payment_type', to='api_user.profiles'),
        ),
    ]
