# Generated by Django 4.1.1 on 2022-11-27 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0010_alter_profiles_payment_type_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('descriptions', models.CharField(max_length=999)),
                ('account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_action', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'history_action',
            },
        ),
    ]
